#ifndef GLINKADULTLEFTHANDDRAGORNDL_H
#define GLINKADULTLEFTHANDDRAGORNDL_H

#include "ultra64.h"
#include "object_link_boy.h"

extern u64 gLinkAdultLeftHandDragornDL_default_gauntlet_1_ci8_png_001_ci8[];
extern u64 gLinkAdultLeftHandDragornDL_default_gauntlet_1_ci8_png_001_pal_rgba16[];
extern u64 gLinkAdultLeftHandDragornDL_default_gauntlet_2_ci8_png_001_ci8[];
extern u64 gLinkAdultLeftHandDragornDL_default_gauntlet_2_ci8_png_001_pal_rgba16[];
extern u64 gLinkAdultLeftHandDragornDL_hand_ci8_png_001_ci8[];
extern u64 gLinkAdultLeftHandDragornDL_hand_ci8_png_001_pal_rgba16[];
extern u64 gLinkAdultLeftHandDragornDL_gItemIconDragornTex_rgba32_ci8[];
extern u64 gLinkAdultLeftHandDragornDL_gItemIconDragornTex_rgba32_pal_rgba16[];
extern Vtx gLinkAdultLeftHandDragornDL_gLinkAdultLeftHandDragornDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gLinkAdultLeftHandDragornDL_gLinkAdultLeftHandDragornDL_mesh_layer_Opaque_vtx_0[54];
extern Gfx gLinkAdultLeftHandDragornDL_gLinkAdultLeftHandDragornDL_mesh_layer_Opaque_tri_0[];
extern Vtx gLinkAdultLeftHandDragornDL_gLinkAdultLeftHandDragornDL_mesh_layer_Opaque_vtx_1[18];
extern Gfx gLinkAdultLeftHandDragornDL_gLinkAdultLeftHandDragornDL_mesh_layer_Opaque_tri_1[];
extern Vtx gLinkAdultLeftHandDragornDL_gLinkAdultLeftHandDragornDL_mesh_layer_Opaque_vtx_2[54];
extern Gfx gLinkAdultLeftHandDragornDL_gLinkAdultLeftHandDragornDL_mesh_layer_Opaque_tri_2[];
extern Vtx gLinkAdultLeftHandDragornDL_gLinkAdultLeftHandDragornDL_mesh_layer_Opaque_vtx_3[4];
extern Gfx gLinkAdultLeftHandDragornDL_gLinkAdultLeftHandDragornDL_mesh_layer_Opaque_tri_3[];
extern Gfx mat_gLinkAdultLeftHandDragornDL_f3dlite_material_001_layerOpaque[];
extern Gfx mat_revert_gLinkAdultLeftHandDragornDL_f3dlite_material_001_layerOpaque[];
extern Gfx mat_gLinkAdultLeftHandDragornDL_f3dlite_material_002_layerOpaque[];
extern Gfx mat_revert_gLinkAdultLeftHandDragornDL_f3dlite_material_002_layerOpaque[];
extern Gfx mat_gLinkAdultLeftHandDragornDL_f3dlite_material_003_layerOpaque[];
extern Gfx mat_revert_gLinkAdultLeftHandDragornDL_f3dlite_material_003_layerOpaque[];
extern Gfx mat_gLinkAdultLeftHandDragornDL_f3dlite_material_layerOpaque[];
extern Gfx mat_revert_gLinkAdultLeftHandDragornDL_f3dlite_material_layerOpaque[];
extern Gfx gLinkAdultLeftHandDragornDL[];

#endif
